baseURL = "https://syedtaz.github.io/"
languageCode = "en-us"
title = "(knife)2"
theme = "HugoTex"

[author]
  name = "Tazmilur Saad"
  abstract = "Hi, I'm Taz! I'm currently a junior at Colgate University where I am double majoring in computer science and applied mathematics. Feel free to snoop around!"